In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [3]:
lr = LogisticRegression(solver = 'liblinear', multi_class = 'ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9592592592592593

In [4]:
svm = SVC(gamma = 'auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.4759259259259259

In [5]:
svm = SVC(gamma = 'scale')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [6]:
rf = RandomForestClassifier(n_estimators = 40, criterion = 'entropy')
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9703703703703703

In [7]:
rf = RandomForestClassifier(n_estimators = 100, criterion = 'gini')
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index],digits.data[test_index], digits.target[train_index],digits.target[test_index]

In [11]:
scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
scores_rf.append(get_score(RandomForestClassifier(n_estimators=100, criterion = 'gini'), X_train, X_test, y_train, y_test))

In [12]:
scores_logistic

[0.9098497495826378]

In [13]:
scores_svm

[0.5125208681135225]

In [14]:
scores_rf

[0.9332220367278798]

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data, digits.target, cv = 3)

array([0.89482471, 0.95325543, 0.90984975])

In [17]:
cross_val_score(SVC(gamma='auto'),digits.data, digits.target, cv = 3)

array([0.38063439, 0.41068447, 0.51252087])

In [18]:
cross_val_score(RandomForestClassifier(n_estimators=100),digits.data, digits.target, cv = 3)

array([0.93823038, 0.96160267, 0.92654424])

In [19]:
scores1 = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data, digits.target, cv = 10)
np.average(scores1)

0.9259745499689634

In [20]:
scores2 = cross_val_score(SVC(gamma='auto'),digits.data, digits.target, cv = 10)
np.average(scores2)

0.48198324022346367

In [21]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=100),digits.data, digits.target, cv = 10)
np.average (scores3)

0.9510180012414648