In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import warnings
warnings.filterwarnings("ignore")

In [5]:
df = pd.read_csv('Prices.csv')
df

AREA   PRICE
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
X = df.drop(['PRICE'], axis = 1)
X

AREA
0  2600
1  3000
2  3200
3  3600
4  4000

In [7]:
y = df.drop(['AREA'], axis = 1)
y

PRICE
0  550000
1  565000
2  610000
3  680000
4  725000

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['AREA']],df.PRICE)

LinearRegression()

In [9]:
plt.xlabel('AREA(sq. ft)')
plt.ylabel('PRICE(USD)') 
plt.scatter(df.AREA, df.PRICE, color = 'Red') # plotting the scatter plot
plt.plot(df.AREA, reg.predict(df[['AREA']]),color = 'blue') # fitting the curve

In [10]:
reg.coef_

array([135.78767123])

In [11]:
reg.intercept_

180616.43835616432

In [12]:
135.78767123*3300+180616.43835616432

628715.7534151643

In [13]:
reg.predict([[3300]])

array([628715.75342466])

In [14]:
reg.predict([[5000]])

array([859554.79452055])

In [19]:
R_square = reg.score(X,y)
R_square

0.9584301138199486